### ISSUE TITLE
expose python shell startup command as argument

### ISSUE THREAD

**Issue by vereszol** [nokia/crl-interactivesessions#50]
Some Linux distributions like Fedora remove ``/usr/bin/python`` symlink together with Python 2 support, leaving only ``/usr/bin/python3``.
This leads to "command not found" error when pushing PythonShell during initialization of SelfRepairingSession - other parts of the code like MsgPythonShell are affected as well.

Possible solutions:
1. handle terminal error "python: command not found" and re-issue 'python3' command
2. parametrize SelfRepairingSession constructor to accept startup command for Python shell. This solution probably needs other changes as well, i.e. for MsgPythonShell 
3. parametrize BashShell to enable defining local alias for commands like ``python`` - for example by extending meaning of 'init_env' argument. This solution needs changes to SelfRepairingSession as well - part of solution 2.

Proposal for changing ``init_env`` argument in ``BashShell.__init__()``:
- now it is a path to a file to be sourced
- could be changed to be a path or a string content to be interpreted/loaded, with 'protocol' marker in the beginning:
   ``init_env=<path|content>:<path or string>``
- to make it backward compatible, if no protocol defined, then file: is expected
   for example: ``init_env='content: alias python=python3'``

**Comment by petrieh** [comment]
The solution 1 is not a generic solution as it heavily depends on the platform. The assumption here is that the controlling terminal (which has usually the platform default environment) has either **python** or **python3** defined in the path. In general, **python** can be defined various ways not following this specified pattern. Therefore, it would be better that the definition of **python** is very controlling terminal state specific. As the controlling terminal state is managed by **shells** the solution 3 is the best from these solutions. Of course the solution 2 would not solve anything else but **SelfRepairingSession** case.
